import React, { useState } from "react";
import type { PersonaDef, HeatMetricConfig } from "../types";

interface Props {
  persona: PersonaDef;
  heatMetrics: HeatMetricConfig[];
  onClose: () => void;
}

type Status = "idle" | "success";

function buildMetricDql(metric: HeatMetricConfig): string {
  if (metric.dqlQuery?.trim()) {
    return metric.dqlQuery
      .replace(/\$\{from\}/g, "now()-7d")
      .replace(/\$\{to\}/g, "now()")
      .replace(/\$\{interval\}/g, "1h");
  }
  if (!metric.metricKey) return "fetch logs | limit 1";
  if (metric.type === "ratio" && metric.denominatorKey) {
    return [
      `timeseries numerator=${metric.aggregation}(${metric.metricKey}), denominator=${metric.aggregation}(${metric.denominatorKey}), from:now()-7d, to:now()`,
      `| fieldsAdd totalNumerator=arraySum(numerator), totalDenominator=arraySum(denominator)`,
      `| fieldsAdd ratePct=if(totalDenominator>0, toDouble(totalNumerator)/toDouble(totalDenominator)*100, else:0.0)`,
    ].join("\n");
  }
  return [
    `timeseries value=${metric.aggregation}(${metric.metricKey}), from:now()-7d, to:now()`,
    `| fieldsAdd avgValue=arrayAvg(value)`,
  ].join("\n");
}

function buildWorkflow(personaLabel: string, heatMetrics: HeatMetricConfig[], email: string) {
  const tasks: Record<string, unknown> = {};
  const n = heatMetrics.length;
  const halfN = Math.floor(n / 2);
  const promptNames: string[] = [];

  heatMetrics.forEach((metric, i) => {
    const queryName = `metric_${i}_query`;
    const promptName = `metric_${i}_prompt`;
    promptNames.push(promptName);
    const xPos = i - halfN;

    tasks[queryName] = {
      name: queryName,
      input: { query: buildMetricDql(metric) },
      action: "dynatrace.automations:execute-dql-query",
      position: { x: xPos, y: 1 },
      description: `Query ${metric.label} data for last 7 days`,
      predecessors: [],
    };

    tasks[promptName] = {
      name: promptName,
      input: {
        config: "disabled",
        prompt: `Provide a report for the following use case:\n## ${metric.label} Analysis Report`,
        autoTrim: true,
        instruction: "Provide a Summary, Insights, Observations and Recommendations.",
        supplementary: `Format examples in tables instead of bulleted lists.\nWhere applicable convert units for readability, e.g. 1000000000 bytes is 1 GiB.\nUse this analysis:\n{{result("${queryName}")["records"]}}\n`,
      },
      action: "dynatrace.davis.copilot.workflow.actions:davis-copilot",
      position: { x: xPos, y: 2 },
      conditions: { states: { [queryName]: "OK" } },
      description: `Analyze ${metric.label} with Dynatrace Intelligence`,
      predecessors: [queryName],
    };
  });

  // Overall analysis — waits for all per-metric prompts
  const overallStates: Record<string, string> = {};
  promptNames.forEach((p) => { overallStates[p] = "OK"; });
  const supplementaryParts = promptNames.map((p) => `{{result("${p}").text}}`).join("\n");

  tasks["overall_prompt"] = {
    name: "overall_prompt",
    input: {
      config: "disabled",
      prompt: `Provide a comprehensive weekly report for the following use case:\n## NavigatorIQ ${personaLabel} Weekly Report`,
      autoTrim: true,
      instruction: "Provide an Executive Summary, Key Findings, Trends, and Actionable Recommendations.",
      supplementary: `Format examples in tables instead of bulleted lists.\nUse this combined metric analysis:\n${supplementaryParts}\n`,
    },
    action: "dynatrace.davis.copilot.workflow.actions:davis-copilot",
    position: { x: 0, y: 3 },
    conditions: { states: overallStates },
    description: "Overall persona analysis with Dynatrace Intelligence",
    predecessors: [...promptNames],
  };

  // Email task
  tasks["email_report"] = {
    name: "email_report",
    input: {
      cc: [],
      to: [email],
      bcc: [],
      content: `{{result("overall_prompt").text}}\n\n---`,
      subject: `NavigatorIQ ${personaLabel} Weekly Report`,
    },
    action: "dynatrace.email:send-email",
    position: { x: 0, y: 4 },
    conditions: { states: { overall_prompt: "OK" } },
    description: "Send weekly NavigatorIQ persona report",
    predecessors: ["overall_prompt"],
  };

  const today = new Date().toISOString().split("T")[0];

  return {
    title: `NavigatorIQ ${personaLabel} Weekly Report`,
    description: `Weekly ${personaLabel} persona performance report generated by NavigatorIQ. Runs every Monday at 8:00 AM.`,
    ownerType: "USER",
    isPrivate: true,
    schemaVersion: 4,
    trigger: {
      schedule: {
        isActive: true,
        trigger: {
          type: "cron",
          cron: "0 8 * * 1",
        },
        timezone: "America/New_York",
        filterParameters: {
          earliestStart: today,
        },
        inputs: {},
      },
    },
    result: null,
    type: "STANDARD",
    input: {},
    hourlyExecutionLimit: 10,
    guide: `# NavigatorIQ ${personaLabel} Weekly Report\nThis workflow runs every Monday at 8:00 AM and sends a ${personaLabel} persona performance report. It queries ${n} metric${n !== 1 ? "s" : ""} for the last 7 days, analyzes each with Dynatrace Intelligence, then compiles an overall summary and emails the results.`,
    tasks,
  };
}

// 3×3 grid icon matching the Automate button's appearance
function GridIcon({ size = 16 }: { size?: number }) {
  const dot = Math.round(size * 0.22);
  const gap = Math.round(size * 0.11);
  return (
    <span
      style={{
        display: "inline-grid",
        gridTemplateColumns: `repeat(3, ${dot}px)`,
        gap: `${gap}px`,
        verticalAlign: "middle",
        lineHeight: 0,
      }}
    >
      {Array(9).fill(null).map((_, i) => (
        <span
          key={i}
          style={{ width: dot, height: dot, background: "currentColor", borderRadius: 1, display: "block" }}
        />
      ))}
    </span>
  );
}

export function AutomateModal({ persona, heatMetrics, onClose }: Props) {
  const [email, setEmail] = useState("");
  const [status, setStatus] = useState<Status>("idle");

  const isValidEmail = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);

  const handleDownload = () => {
    if (!isValidEmail) return;
    const workflow = buildWorkflow(persona.label, heatMetrics, email);
    const blob = new Blob([JSON.stringify(workflow, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `NavigatorIQ_${persona.label.replace(/\s+/g, "_")}_Weekly_Report.workflow.json`;
    a.click();
    URL.revokeObjectURL(url);
    setStatus("success");
  };

  return (
    <div
      style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.72)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 2000, backdropFilter: "blur(4px)" }}
      onClick={onClose}
    >
      <div
        style={{ background: "linear-gradient(135deg,rgba(9,12,22,0.99) 0%,rgba(14,18,34,0.99) 100%)", border: "1px solid rgba(69,137,255,0.3)", borderRadius: 14, padding: 28, width: 460, maxWidth: "calc(100vw - 40px)", boxShadow: "0 20px 60px rgba(0,0,0,0.6)" }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 20 }}>
          <span style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", width: 28, height: 28, background: "#4589FF", borderRadius: 7, color: "#fff", flexShrink: 0 }}>
            <GridIcon size={14} />
          </span>
          <span style={{ fontSize: 15, fontWeight: 800, color: "#fff" }}>Automate Weekly Report</span>
          <button onClick={onClose} style={{ marginLeft: "auto", background: "none", border: "none", color: "rgba(255,255,255,0.4)", fontSize: 18, cursor: "pointer", lineHeight: 1, padding: "2px 6px" }}>✕</button>
        </div>

        {/* Workflow summary card */}
        <div style={{ background: "rgba(69,137,255,0.08)", border: "1px solid rgba(69,137,255,0.2)", borderRadius: 9, padding: "12px 14px", marginBottom: 18 }}>
          <div style={{ fontSize: 11, color: "#7ab4ff", fontWeight: 700, marginBottom: 3, textTransform: "uppercase", letterSpacing: "0.06em" }}>Workflow Name</div>
          <div style={{ fontSize: 13, color: "#fff", fontWeight: 600 }}>NavigatorIQ {persona.label} Weekly Report</div>
          <div style={{ fontSize: 11, color: "rgba(255,255,255,0.4)", marginTop: 5 }}>
            Every Monday at 8:00 AM · {heatMetrics.length} metric{heatMetrics.length !== 1 ? "s" : ""} · Last 7 days each run
          </div>
        </div>

        {/* Metrics pills */}
        <div style={{ marginBottom: 18 }}>
          <div style={{ fontSize: 11, fontWeight: 700, color: "rgba(255,255,255,0.45)", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 8 }}>Metrics Included</div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 5 }}>
            {heatMetrics.map((m, i) => (
              <span key={i} style={{ fontSize: 11, padding: "3px 9px", background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.12)", borderRadius: 12, color: "rgba(255,255,255,0.65)" }}>
                {m.label}
              </span>
            ))}
          </div>
        </div>

        {/* Workflow flow description */}
        <div style={{ marginBottom: 18, padding: "10px 14px", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 8 }}>
          <div style={{ fontSize: 11, color: "rgba(255,255,255,0.35)", lineHeight: 1.7 }}>
            <span style={{ color: "rgba(255,255,255,0.55)", fontWeight: 600 }}>Flow: </span>
            {heatMetrics.length} DQL queries
            <span style={{ color: "rgba(69,137,255,0.7)", margin: "0 4px" }}>→</span>
            {heatMetrics.length} Dynatrace Intelligence analyses
            <span style={{ color: "rgba(69,137,255,0.7)", margin: "0 4px" }}>→</span>
            1 overall analysis
            <span style={{ color: "rgba(69,137,255,0.7)", margin: "0 4px" }}>→</span>
            email
          </div>
        </div>

        {/* Email input */}
        <div style={{ marginBottom: 20 }}>
          <label style={{ display: "block", fontSize: 11, fontWeight: 700, color: "rgba(255,255,255,0.5)", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 7 }}>
            Send Report To
          </label>
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="your@email.com"
            disabled={status === "success"}
            autoFocus
            style={{ width: "100%", boxSizing: "border-box", background: "rgba(255,255,255,0.05)", border: `1px solid ${email && !isValidEmail ? "rgba(239,68,68,0.5)" : "rgba(255,255,255,0.15)"}`, borderRadius: 8, padding: "10px 12px", color: "#fff", fontSize: 13, outline: "none" }}
            onKeyDown={(e) => { if (e.key === "Enter" && isValidEmail) handleDownload(); }}
          />
        </div>

        {/* Success banner */}
        {status === "success" && (
          <div style={{ background: "rgba(16,185,129,0.1)", border: "1px solid rgba(16,185,129,0.3)", borderRadius: 8, padding: "12px 14px", marginBottom: 16 }}>
            <div style={{ fontSize: 13, color: "#34D399", fontWeight: 700, marginBottom: 5 }}>✓ Workflow JSON downloaded!</div>
            <div style={{ fontSize: 11, color: "rgba(255,255,255,0.6)", lineHeight: 1.7 }}>
              <strong style={{ color: "rgba(255,255,255,0.85)" }}>To activate:</strong><br />
              1. Open the <strong>Workflows</strong> app in Dynatrace<br />
              2. Click <strong>Upload</strong> (top-right) and select the downloaded file<br />
              3. The workflow runs every Monday at 8:00 AM and emails <strong>{email}</strong>
            </div>
          </div>
        )}

        {/* Actions */}
        <div style={{ display: "flex", gap: 10, justifyContent: "flex-end" }}>
          <button
            onClick={onClose}
            style={{ padding: "9px 18px", borderRadius: 8, border: "1px solid rgba(255,255,255,0.15)", background: "transparent", color: "rgba(255,255,255,0.6)", fontSize: 13, cursor: "pointer", fontWeight: 500 }}
          >
            {status === "success" ? "Close" : "Cancel"}
          </button>
          <button
            onClick={handleDownload}
            disabled={!isValidEmail}
            style={{ padding: "9px 20px", borderRadius: 8, border: "none", background: !isValidEmail ? "rgba(69,137,255,0.3)" : "#4589FF", color: "#fff", fontSize: 13, fontWeight: 700, cursor: !isValidEmail ? "not-allowed" : "pointer", transition: "background 0.15s" }}
          >
            {status === "success" ? "↓ Download Again" : "↓ Download Workflow JSON"}
          </button>
        </div>
      </div>
    </div>
  );
}
